### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/flux#2137]
**Describe the bug**
```
ts=2019-06-07T17:59:27.707447931Z caller=release.go:479 component=release err="Object 'Kind' is missing in 'null'"
```

**To Reproduce**
Provide a helm installation with an empty manifest file.  This is natural when the helm file has flags for turning an entire manifest on or off. For example, in file `foo.yaml`:
```
{{ if .Values.useHttps }}
manifest
{{ end }}
```
**Expected behavior**
This is not really an error.  In any case, use the file name if possible in the error message:

```
"Object 'Kind' is missing in 'foo.yaml'"
```

**Comment by hiddeco** [comment]
I tried to install the [mariadb chart](https://github.com/helm/charts/tree/master/stable/mariadb) with the following `HelmRelease`:

```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mariadb
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mariadb
    version: 6.4.2
  values:
    existingSecret: existing
```

With `existingSecret` set, [this should replicate the issue you are describing](https://github.com/helm/charts/blob/master/stable/mariadb/templates/secrets.yaml#L1), I do however not see the reported error in the logs:

```
ts=2019-06-11T08:51:47.484130905Z caller=operator.go:296 component=operator info="enqueuing release" resource=default:helmrelease/mariadb
ts=2019-06-11T08:51:50.698949625Z caller=release.go:167 component=release info="processing release default-mariadb (as default-mariadb)" action=CREATE options="{DryRun:false ReuseName:false}" timeout=300s
ts=2019-06-11T08:53:17.088458837Z caller=operator.go:296 component=operator info="enqueuing release" resource=default:helmrelease/xxx
```

**Comment by hiddeco** [comment]
@derrickburns given the fact that you have not responded since I tried to replicate what you described, I will assume it had something to do with the contents of your chart and not the Helm operator, therefor I will close this issue.

If you disagree with my assumption, please let me know and I will re-open the issue.

**Comment by derrickburns** [comment]
Hmmm.

Please reopen the issue.  I do not know why you could not reproduce it.  I see it often. I will investigate more.

```
│ ts=2019-07-31T08:05:03.109286946Z caller=release.go:568 component=release err="Object 'Kind' ││  is missing in 'null'"                                                                       ││ ts=2019-07-31T08:05:03.119530313Z caller=release.go:568 component=release err="Object 'Kind' ││  is missing in 'null'"                                                                       ││ ts=2019-07-31T08:05:03.125999094Z caller=release.go:568 component=release err="Object 'Kind' ││  is missing in 'null'"                                                                       ││ ts=2019-07-31T08:05:03.127110825Z caller=release.go:568 component=release err="Object 'Kind' ││  is missing in 'null'"                                                                       ││ ts=2019-07-31T08:05:03.134536694Z caller=release.go:568 component=release err="Object 'Kind' ││  is missing in 'null'"                                                                       ││ ts=2019-07-31T08:05:03.147857969Z caller=release.go:568 component=release err="Object 'Kind' ││  is missing in 'null'"                                                                       ││ ts=2019-07-31T08:05:03.153015437Z caller=release.go:568 component=release err="Object 'Kind' ││  is missing in 'null'"                                                                       ││ ts=2019-07-31T08:05:03.153738838Z caller=release.go:568 component=release err="Object 'Kind' ││  is missing in 'null'"                                                                       │
│ ts=2019-07-31T08:05:03.154305817Z caller=release.go:568 component=release err="Object 'Kind' │
│  is missing in 'null'"                                                                       │
│ ts=2019-07-31T08:05:03.158945378Z caller=release.go:568 component=release err="Object 'Kind' │
│  is missing in 'null'"
```

**Comment by IngussNeilands** [comment]
Same here - "Object 'Kind' is missing in 'foo.yaml'"
I would like to suggest adding more details about source of error so we could track in and fix it...

**Comment by hiddeco** [comment]
This has been resolved in https://github.com/fluxcd/helm-operator/pull/47

**Comment by younesehb** [comment]
I am using the latest release of the helm operator v1.0.0-rc6 but I am still getting the error `Object 'Kind' is missing in 'null` 

`
targetNamespace=app-monitoring resource=fluxcd:helmrelease/prometheus-server helmVersion=v3 err="Object 'Kind' is missing in 'null'"
--
  | ts=2020-01-10T14:02:31.321319173Z caller=annotator.go:104 component=release release=prometheus-server targetNamespace=app-monitoring resource=fluxcd:helmrelease/prometheus-server helmVersion=v3 err="Object 'Kind' is missing in 'null'"
  | ts=2020-01-10T14:02:31.321368674Z caller=annotator.go:104 component=release release=prometheus-server targetNamespace=app-monitoring resource=fluxcd:helmrelease/prometheus-server helmVersion=v3 err="Object 'Kind' is missing in 'null'"
`

**Comment by kovalyukm** [comment]
The same issue for stable/prometheus-operator.

Log enries in app=helm-operator:
ts=2020-01-28T14:18:21.694042875Z caller=annotator.go:100 component=release release=test-release targetNamespace=monitoring resource=monitoring:helmrelease/prometheus-operator helmVersion=v3 err="Object 'Kind' is missing in 'null'"
...

**Comment by stefanprodan** [comment]
@kovalyukm please open an issue on the Helm operator repo https://github.com/fluxcd/helm-operator/issues/new/choose and please make sure you're on the latest version v1.0.0-rc8
